apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: jmeter-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: develop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jmeter-service
      app.kubernetes.io/instance: keptn
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jmeter-service
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: develop
    spec:
      containers:
      - name: jmeter-service
        image: keptn/jmeter-service:0.7.3-patch1
        livenessProbe:
          httpGet:
            path: /health
            port: 10999
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8080
        env:
        - name: DT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace
              key: DT_API_TOKEN
              optional: true
        - name: DT_TENANT
          valueFrom:
            secretKeyRef:
              name: dynatrace
              key: DT_TENANT
              optional: true
        - name: EVENTBROKER
          value: 'http://event-broker/keptn'
        - name: DEBUG_KEEP_TEMP_FILES
          value: "false"
      - name: distributor
        image: keptn/distributor:0.7.3
        livenessProbe:
          httpGet:
            path: /health
            port: 10999
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PUBSUB_URL
            value: 'nats://keptn-nats-cluster'
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.events.deployment-finished'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: jmeter-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "192.168.3.91"
    hostnames:
    - "kiab.pcjeffint.com"
    - "git.kiab.pcjeffint.com"
  - ip: "192.168.3.91"
    hostnames:
    - "frontend.keptnorders-staging.kiab.pcjeffint.com"
    - "frontend.keptnorders-production.kiab.pcjeffint.com"
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: jmeter-service
    app.kubernetes.io/instance: keptn
